# -*- coding: utf-8 -*-
"""EdVyro-Task_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kuQN_tU4Y1mFdgCQVm35THZ4gJW4-nWY

# Customer Churn Analysis
## Task 02 — Data Quality and Exploratory Analysis

### Objective

The objective of this project is to audit, clean, and explore a
customer churn dataset.

We will:

- Understand the structure of the dataset
- Check data types
- Identify missing values
- Identify duplicate records
- Detect potential outliers
- Validate important data relationships
- Calculate summary statistics
- Explore customer churn patterns
- Create an analysis-ready cleaned dataset

### Business Question

Which customer characteristics and account behaviors appear to be
associated with customer churn?
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display all columns when viewing DataFrames
pd.set_option('display.max_columns', None)

# Make visualizations easier to read
sns.set_theme(style="whitegrid")

from google.colab import files

uploaded = files.upload()

df = pd.read_csv("customer_churn_sample.csv")

df

df.head()

df.tail()

rows, columns = df.shape

print("Number of rows:", rows)
print("Number of columns:", columns)

print("Column names:\n")

for column in df.columns:
    print("-", column)

df.info()

missing_values = df.isnull().sum()

print("Missing values in each column:")
print(missing_values)

missing_summary = pd.DataFrame({
    "Column": df.columns,
    "Missing Values": df.isnull().sum().values,
    "Missing Percentage": (
        df.isnull().sum().values / len(df) * 100
    ).round(2)
})

missing_summary

duplicate_rows = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_rows)

duplicate_customers = df["CustomerID"].duplicated().sum()

print("Duplicate Customer IDs:", duplicate_customers)

categorical_columns = df.select_dtypes(
    include="object"
).columns

for column in categorical_columns:
    print("\n" + "=" * 50)
    print(column)
    print("=" * 50)
    print(df[column].value_counts())

df.describe()

numeric_columns = df.select_dtypes(
    include=np.number
).columns

print("Numerical columns:")
print(numeric_columns.tolist())

df[numeric_columns].describe().T

outlier_results = []

for column in numeric_columns:

    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[
        (df[column] < lower_bound) |
        (df[column] > upper_bound)
    ]

    outlier_results.append({
        "Column": column,
        "Q1": Q1,
        "Q3": Q3,
        "IQR": IQR,
        "Lower Bound": lower_bound,
        "Upper Bound": upper_bound,
        "Outlier Count": len(outliers)
    })

outlier_summary = pd.DataFrame(outlier_results)

outlier_summary

for column in numeric_columns:

    plt.figure(figsize=(7, 4))

    sns.histplot(
        data=df,
        x=column,
        kde=True
    )

    plt.title(f"Distribution of {column}")
    plt.xlabel(column)
    plt.ylabel("Frequency")

    plt.show()

for column in numeric_columns:

    plt.figure(figsize=(7, 4))

    sns.boxplot(
        x=df[column]
    )

    plt.title(f"Boxplot of {column}")
    plt.xlabel(column)

    plt.show()

churn_counts = df["Churn"].value_counts()

print(churn_counts)

churn_rate = (
    df["Churn"].eq("Yes").mean() * 100
)

print(f"Overall churn rate: {churn_rate:.2f}%")

plt.figure(figsize=(6, 4))

sns.countplot(
    data=df,
    x="Churn"
)

plt.title("Customer Churn Distribution")
plt.xlabel("Churn")
plt.ylabel("Number of Customers")

plt.show()

contract_churn = pd.crosstab(
    df["ContractType"],
    df["Churn"],
    normalize="index"
) * 100

contract_churn

contract_churn.plot(
    kind="bar",
    figsize=(8, 5)
)

plt.title("Churn Distribution by Contract Type")
plt.xlabel("Contract Type")
plt.ylabel("Percentage")
plt.xticks(rotation=0)

plt.show()

df["TenureGroup"] = pd.cut(
    df["TenureMonths"],
    bins=[-1, 12, 24, 36, 100],
    labels=[
        "0-12 months",
        "13-24 months",
        "25-36 months",
        "37+ months"
    ]
)

df[["TenureMonths", "TenureGroup"]].head()

tenure_churn = pd.crosstab(
    df["TenureGroup"],
    df["Churn"],
    normalize="index"
) * 100

tenure_churn

tenure_churn.plot(
    kind="bar",
    figsize=(8, 5)
)

plt.title("Churn Distribution by Tenure Group")
plt.xlabel("Tenure Group")
plt.ylabel("Percentage")
plt.xticks(rotation=0)

plt.show()

payment_churn = pd.crosstab(
    df["PaymentMethod"],
    df["Churn"],
    normalize="index"
) * 100

payment_churn

payment_churn.plot(
    kind="bar",
    figsize=(9, 5)
)

plt.title("Churn Distribution by Payment Method")
plt.xlabel("Payment Method")
plt.ylabel("Percentage")
plt.xticks(rotation=45)

plt.show()

subscription_churn = pd.crosstab(
    df["SubscriptionType"],
    df["Churn"],
    normalize="index"
) * 100

subscription_churn

support_churn = pd.crosstab(
    df["SupportTickets"],
    df["Churn"],
    normalize="index"
) * 100

support_churn

support_churn.plot(
    kind="bar",
    figsize=(8, 5)
)

plt.title("Churn Distribution by Support Tickets")
plt.xlabel("Number of Support Tickets")
plt.ylabel("Percentage")

plt.show()

correlation_matrix = df[numeric_columns].corr()

correlation_matrix

plt.figure(figsize=(10, 7))

sns.heatmap(
    correlation_matrix,
    annot=True,
    fmt=".2f",
    cmap="coolwarm"
)

plt.title("Correlation Matrix")

plt.show()

df["ExpectedTotalCharges"] = (
    df["MonthlyCharges"] * df["TenureMonths"]
)

df["ChargeDifference"] = (
    df["TotalCharges"] -
    df["ExpectedTotalCharges"]
)

df[
    [
        "MonthlyCharges",
        "TenureMonths",
        "TotalCharges",
        "ExpectedTotalCharges",
        "ChargeDifference"
    ]
]

inconsistent_charges = df[
    ~np.isclose(
        df["TotalCharges"],
        df["ExpectedTotalCharges"],
        atol=0.01
    )
]

print(
    "Number of inconsistent records:",
    len(inconsistent_charges)
)

cleaned_df = df.copy()

cleaned_df = cleaned_df.drop(
    columns=[
        "ExpectedTotalCharges",
        "ChargeDifference"
    ],
    errors="ignore"
)

cleaned_df

cleaned_df.head()

cleaned_df.tail()

print("Rows:", cleaned_df.shape[0])
print("Columns:", cleaned_df.shape[1])

print("\nTotal missing values:",
      cleaned_df.isnull().sum().sum())

print("Duplicate rows:",
      cleaned_df.duplicated().sum())

cleaned_df.to_csv(
    "customer_churn_cleaned.csv",
    index=False
)

print("Cleaned dataset successfully created!")

from google.colab import files

files.download("customer_churn_cleaned.csv")

"""# Conclusion

## Data Quality

The customer churn dataset was systematically audited for:

- Missing values
- Duplicate records
- Duplicate customer IDs
- Incorrect data types
- Numerical outliers
- Inconsistent charge calculations

The cleaned dataset was validated and exported as an
analysis-ready CSV file.

## Exploratory Findings

The exploratory analysis was used to investigate relationships between
customer churn and:

- Contract type
- Customer tenure
- Payment method
- Subscription type
- Support-ticket volume
- Numerical customer characteristics

The analysis provides useful initial signals for further investigation.

## Important Limitation

The dataset is small and synthetic. Therefore, the observed patterns
should be treated as exploratory findings rather than statistically
generalizable conclusions about a real customer population.

## Next Step

The cleaned dataset will be used in Task 03 to build a business KPI
dashboard containing:

- Churn Rate
- Retention Rate
- Revenue at Risk
- Customer Segments
- Interactive Filters
- Business-focused Visualizations
"""